# Imagem base
FROM python:3.10-slim

# Variáveis de ambiente
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# copiar requirements e instalar
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# copiar código
COPY . .

# expor porta
EXPOSE 8000

# comando default
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]